[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet build Portfolio.API/Portfolio.API.csproj -c Release"]

[start]
cmd = "dotnet run --project Portfolio.API/Portfolio.API.csproj --urls http://0.0.0.0:$PORT --no-build"
